services:
  - type: web
    name: resume-api
    env: python
    buildCommand: ""
    startCommand: uvicorn api_wrapper:app_api --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
